package com.clw.aivideotranslator

import android.media.MediaExtractor
import android.media.MediaFormat
import android.util.Base64
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.clw.aivideotranslator.semantic.AudioIntervalUs
import com.clw.aivideotranslator.semantic.AudioTimeUs
import com.clw.aivideotranslator.semantic.ClockVerificationStatus
import com.clw.aivideotranslator.semantic.PresentationTimeUs
import com.clw.aivideotranslator.semantic.SampleClockMap
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.security.MessageDigest
import java.util.UUID
import kotlin.math.sqrt
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * X001 Android presentation-origin falsifier.
 *
 * MP4 edit-list offsets are normalized differently by Android MediaExtractor across API levels, so
 * this test deliberately uses a synthetic MPEG-TS fixture whose AAC packets carry nonzero transport
 * PTS directly. The fixture is stored as base64 text for repository portability and was generated by:
 *
 * ffmpeg -f lavfi -i sine=frequency=440:sample_rate=48000:duration=0.7 \
 *   -af 'asetpts=PTS+0.5/TB' -c:a aac -b:a 64k -ar 48000 -ac 1 \
 *   -f mpegts -mpegts_copyts 1 x001_delayed_tone.ts
 *
 * The test independently reads the first audio sample time through MediaExtractor, then runs the
 * production SttAudioPreparer and proves that prepared-sample zero maps back to that nonzero source
 * presentation origin rather than silently assuming presentation zero.
 */
@RunWith(AndroidJUnit4::class)
class X001PresentationClockInstrumentedTest {
    private lateinit var root: File

    @Before
    fun setUp() {
        val targetContext = InstrumentationRegistry.getInstrumentation().targetContext
        root = File(targetContext.cacheDir, "x001-clock-${UUID.randomUUID()}").apply {
            check(mkdirs() || isDirectory)
        }
    }

    @After
    fun tearDown() {
        root.deleteRecursively()
    }

    @Test
    fun delayedContainerPtsBecomesPreparedSamplePresentationOrigin() {
        val delayed = decodeDelayedTransportFixture()
        val independentlyObservedStartUs = firstAudioSampleTimeUs(delayed)

        assertTrue(
            "fixture must expose a clearly nonzero audio presentation origin, observed=$independentlyObservedStartUs",
            independentlyObservedStartUs in MIN_EXPECTED_DELAY_US..MAX_EXPECTED_DELAY_US,
        )

        val wav = File(root, "prepared.wav")
        val preparation = SttAudioPreparer.preparePrivateSourceFirstMinute(delayed, wav).getOrThrow()
        val profile = preparation.profile

        assertEquals(independentlyObservedStartUs, profile.sourceStartUs)
        assertEquals(48_000, profile.sampleRateHz)
        assertEquals(1, profile.channelCount)
        assertEquals(
            profile.sourceStartUs + preparation.provenance.pcmFrameCount * 1_000_000L / profile.sampleRateHz,
            profile.sourceEndUs,
        )

        // Decoder output is sample-relative: the container delay must be represented by sourceStartUs,
        // not prepended as half a second of synthetic PCM silence.
        assertTrue(
            "prepared sample must begin with the synthetic tone",
            firstWindowRms(wav, profile.sampleRateHz) > 500.0,
        )

        val verifiedClock = SampleClockMap(
            presentationOrigin = PresentationTimeUs(independentlyObservedStartUs),
            precisionUs = 1L,
            status = ClockVerificationStatus.VERIFIED_AFFINE,
            evidenceProfile = "android-mediaextractor-mpegts-delayed-aac-v4",
        )
        val mapped = verifiedClock.mapVerified(
            AudioIntervalUs(AudioTimeUs(0L), AudioTimeUs(100_000L))
        )
        assertEquals(independentlyObservedStartUs, mapped.start.value)
        assertEquals(independentlyObservedStartUs + 100_000L, mapped.end.value)
    }

    private fun decodeDelayedTransportFixture(): File {
        val testContext = InstrumentationRegistry.getInstrumentation().context
        val encoded = testContext.assets.open("source_capture/x001_delayed_tone.ts.b64")
            .bufferedReader()
            .use { it.readText() }
        val compact = buildString(encoded.length) {
            encoded.forEach { ch ->
                when {
                    ch in 'A'..'Z' ||
                        ch in 'a'..'z' ||
                        ch in '0'..'9' ||
                        ch == '+' || ch == '/' || ch == '=' -> append(ch)
                    ch == '\r' || ch == '\n' || ch == ' ' || ch == '\t' -> Unit
                    else -> error(
                        "unexpected base64 fixture character U+${ch.code.toString(16).uppercase()}"
                    )
                }
            }
        }
        val bytes = Base64.decode(compact, Base64.NO_WRAP)
        assertEquals(EXPECTED_TS_SHA256, sha256(bytes))
        return File(root, "x001_delayed_tone.ts").apply { writeBytes(bytes) }
    }

    private fun firstAudioSampleTimeUs(file: File): Long {
        val extractor = MediaExtractor()
        try {
            extractor.setDataSource(file.absolutePath)
            val trackIndex = findAudioTrack(extractor)
            extractor.selectTrack(trackIndex)
            return extractor.sampleTime
        } finally {
            extractor.release()
        }
    }

    private fun findAudioTrack(extractor: MediaExtractor): Int =
        (0 until extractor.trackCount).firstOrNull { index ->
            extractor.getTrackFormat(index).getString(MediaFormat.KEY_MIME)?.startsWith("audio/") == true
        } ?: error("fixture has no audio track")

    private fun firstWindowRms(wav: File, sampleRateHz: Int): Double {
        val bytes = wav.readBytes()
        require(bytes.size > WAV_HEADER_BYTES) { "prepared WAV is empty" }
        val wantedSamples = sampleRateHz / 10
        val availableSamples = (bytes.size - WAV_HEADER_BYTES) / 2
        val count = minOf(wantedSamples, availableSamples)
        require(count > 0) { "prepared WAV has no PCM samples" }
        val pcm = ByteBuffer.wrap(bytes, WAV_HEADER_BYTES, count * 2).order(ByteOrder.LITTLE_ENDIAN)
        var sumSquares = 0.0
        repeat(count) {
            val sample = pcm.short.toDouble()
            sumSquares += sample * sample
        }
        return sqrt(sumSquares / count.toDouble())
    }

    private fun sha256(bytes: ByteArray): String =
        MessageDigest.getInstance("SHA-256")
            .digest(bytes)
            .joinToString("") { "%02x".format(it) }

    private companion object {
        const val WAV_HEADER_BYTES = 44
        const val MIN_EXPECTED_DELAY_US = 400_000L
        const val MAX_EXPECTED_DELAY_US = 600_000L
        const val EXPECTED_TS_SHA256 = "c18f1c0f62644d11c52661adcde7c7f07ddce3aef4bef527c0a4998ae7e522b0"
    }
}
